[tool.poetry]
name = "insecure"
version = "0.1.0"
description = ""
authors = ["ash <ah37@sanger.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.105"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
